// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: analytics.proto

package analyticspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PurchaseEvent is emitted by the core API whenever a purchase is committed.
type PurchaseEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PurchaseId    string                 `protobuf:"bytes,1,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TierId        string                 `protobuf:"bytes,3,opt,name=tier_id,json=tierId,proto3" json:"tier_id,omitempty"`
	BuyerId       string                 `protobuf:"bytes,4,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	AmountCents   int64                  `protobuf:"varint,5,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	Quantity      int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseEvent) Reset() {
	*x = PurchaseEvent{}
	mi := &file_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseEvent) ProtoMessage() {}

func (x *PurchaseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseEvent.ProtoReflect.Descriptor instead.
func (*PurchaseEvent) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *PurchaseEvent) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

func (x *PurchaseEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PurchaseEvent) GetTierId() string {
	if x != nil {
		return x.TierId
	}
	return ""
}

func (x *PurchaseEvent) GetBuyerId() string {
	if x != nil {
		return x.BuyerId
	}
	return ""
}

func (x *PurchaseEvent) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *PurchaseEvent) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *PurchaseEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

type RecordAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	TotalEvents   uint64                 `protobuf:"varint,2,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordAck) Reset() {
	*x = RecordAck{}
	mi := &file_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordAck) ProtoMessage() {}

func (x *RecordAck) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordAck.ProtoReflect.Descriptor instead.
func (*RecordAck) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *RecordAck) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

func (x *RecordAck) GetTotalEvents() uint64 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *StatsRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type EventStats struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EventId             string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TotalRevenueCents   int64                  `protobuf:"varint,2,opt,name=total_revenue_cents,json=totalRevenueCents,proto3" json:"total_revenue_cents,omitempty"`
	TicketsSold         int64                  `protobuf:"varint,3,opt,name=tickets_sold,json=ticketsSold,proto3" json:"tickets_sold,omitempty"`
	SalesVelocityPerMin float64                `protobuf:"fixed64,4,opt,name=sales_velocity_per_min,json=salesVelocityPerMin,proto3" json:"sales_velocity_per_min,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EventStats) Reset() {
	*x = EventStats{}
	mi := &file_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStats) ProtoMessage() {}

func (x *EventStats) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStats.ProtoReflect.Descriptor instead.
func (*EventStats) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *EventStats) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventStats) GetTotalRevenueCents() int64 {
	if x != nil {
		return x.TotalRevenueCents
	}
	return 0
}

func (x *EventStats) GetTicketsSold() int64 {
	if x != nil {
		return x.TicketsSold
	}
	return 0
}

func (x *EventStats) GetSalesVelocityPerMin() float64 {
	if x != nil {
		return x.SalesVelocityPerMin
	}
	return 0
}

var File_analytics_proto protoreflect.FileDescriptor

const file_analytics_proto_rawDesc = "" +
	"\n" +
	"\x0fanalytics.proto\x12\fanalytics.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfb\x01\n" +
	"\rPurchaseEvent\x12\x1f\n" +
	"\vpurchase_id\x18\x01 \x01(\tR\n" +
	"purchaseId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x17\n" +
	"\atier_id\x18\x03 \x01(\tR\x06tierId\x12\x19\n" +
	"\bbuyer_id\x18\x04 \x01(\tR\abuyerId\x12!\n" +
	"\famount_cents\x18\x05 \x01(\x03R\vamountCents\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\x12;\n" +
	"\voccurred_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"J\n" +
	"\tRecordAck\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\x12!\n" +
	"\ftotal_events\x18\x02 \x01(\x04R\vtotalEvents\")\n" +
	"\fStatsRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"\xaf\x01\n" +
	"\n" +
	"EventStats\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12.\n" +
	"\x13total_revenue_cents\x18\x02 \x01(\x03R\x11totalRevenueCents\x12!\n" +
	"\ftickets_sold\x18\x03 \x01(\x03R\vticketsSold\x123\n" +
	"\x16sales_velocity_per_min\x18\x04 \x01(\x01R\x13salesVelocityPerMin2\x9c\x01\n" +
	"\x10AnalyticsService\x12F\n" +
	"\fRecordStream\x12\x1b.analytics.v1.PurchaseEvent\x1a\x17.analytics.v1.RecordAck(\x01\x12@\n" +
	"\bGetStats\x12\x1a.analytics.v1.StatsRequest\x1a\x18.analytics.v1.EventStatsB7Z5github.com/v-shah07/event-ticketing/proto/analyticspbb\x06proto3"

var (
	file_analytics_proto_rawDescOnce sync.Once
	file_analytics_proto_rawDescData []byte
)

func file_analytics_proto_rawDescGZIP() []byte {
	file_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)))
	})
	return file_analytics_proto_rawDescData
}

var file_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_analytics_proto_goTypes = []any{
	(*PurchaseEvent)(nil),         // 0: analytics.v1.PurchaseEvent
	(*RecordAck)(nil),             // 1: analytics.v1.RecordAck
	(*StatsRequest)(nil),          // 2: analytics.v1.StatsRequest
	(*EventStats)(nil),            // 3: analytics.v1.EventStats
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_analytics_proto_depIdxs = []int32{
	4, // 0: analytics.v1.PurchaseEvent.occurred_at:type_name -> google.protobuf.Timestamp
	0, // 1: analytics.v1.AnalyticsService.RecordStream:input_type -> analytics.v1.PurchaseEvent
	2, // 2: analytics.v1.AnalyticsService.GetStats:input_type -> analytics.v1.StatsRequest
	1, // 3: analytics.v1.AnalyticsService.RecordStream:output_type -> analytics.v1.RecordAck
	3, // 4: analytics.v1.AnalyticsService.GetStats:output_type -> analytics.v1.EventStats
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_analytics_proto_init() }
func file_analytics_proto_init() {
	if File_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_proto_msgTypes,
	}.Build()
	File_analytics_proto = out.File
	file_analytics_proto_goTypes = nil
	file_analytics_proto_depIdxs = nil
}
