apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  namespace: event-ticketing
  labels:
    app: analytics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: ghcr.io/v-shah07/event-ticketing-analytics:latest
          ports:
            - containerPort: 9100
              name: grpc
          envFrom:
            - configMapRef:
                name: api-config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: analytics
  namespace: event-ticketing
spec:
  selector:
    app: analytics
  ports:
    - name: grpc
      port: 9100
      targetPort: 9100
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: analytics
  namespace: event-ticketing
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analytics
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
