// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package discovery

import (
	"time"
)

type Event struct {
	ID             string     `json:"id"`
	Title          string     `json:"title"`
	Description    string     `json:"description"`
	Category       string     `json:"category"`
	Venue          string     `json:"venue"`
	Lat            *float64   `json:"lat,omitempty"`
	Lng            *float64   `json:"lng,omitempty"`
	State          string     `json:"state"`
	StartsAt       *time.Time `json:"startsAt,omitempty"`
	MinPriceCents  *int       `json:"minPriceCents,omitempty"`
	Tiers          []*Tier    `json:"tiers"`
	DistanceMeters *float64   `json:"distanceMeters,omitempty"`
	TrendingScore  float64    `json:"trendingScore"`
}

// EventFilter combines all discovery dimensions. Any subset may be supplied; they
// are ANDed together and resolved in a single query.
type EventFilter struct {
	Category      *string    `json:"category,omitempty"`
	StartsAfter   *time.Time `json:"startsAfter,omitempty"`
	StartsBefore  *time.Time `json:"startsBefore,omitempty"`
	MinPriceCents *int       `json:"minPriceCents,omitempty"`
	MaxPriceCents *int       `json:"maxPriceCents,omitempty"`
	Near          *GeoFilter `json:"near,omitempty"`
}

type GeoFilter struct {
	Lat          float64 `json:"lat"`
	Lng          float64 `json:"lng"`
	RadiusMeters float64 `json:"radiusMeters"`
}

type Query struct {
}

type Tier struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	PriceCents int    `json:"priceCents"`
	Capacity   int    `json:"capacity"`
	Sold       int    `json:"sold"`
	Remaining  int    `json:"remaining"`
}
