package discovery

import (
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/redis/go-redis/v9"
)

// Resolver is the gqlgen root resolver; it carries the datastore dependencies.
//
// This file is not regenerated by gqlgen.
type Resolver struct {
	Pool  *pgxpool.Pool
	Redis *redis.Client
}
