package discovery

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
)

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context, filter *EventFilter) ([]*Event, error) {
	events, err := queryEvents(ctx, r.Pool, r.Redis, filter)
	if err != nil {
		return nil, err
	}
	if events == nil {
		events = []*Event{}
	}
	return events, nil
}

// EventsNearMe is the resolver for the eventsNearMe field.
func (r *queryResolver) EventsNearMe(ctx context.Context, lat float64, lng float64, radiusMeters float64) ([]*Event, error) {
	return r.Events(ctx, &EventFilter{
		Near: &GeoFilter{Lat: lat, Lng: lng, RadiusMeters: radiusMeters},
	})
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
